### ISSUE TITLE
Chromosome language needs clean up?

### ISSUE THREAD

**Issue by joshuahedlund** [stjude/learngenomics.dev#16]
On [Cells, Chromosomes, and Genomes](https://learngenomics.dev/docs/biological-foundations/cells-genomes-dna-chromosomes), it says:

> Each chromosome is composed of two DNA molecules (one from your father and one from your mother) and packaging proteins, or histones, that keep the DNA string neatly wound and help control which gene products are made in a given cell. For humans, there are normally 22 autosomes (chromosomes shared by both sexes) and a pair of sex chromosomes (XX for females or XY for males). Autosomes are numbered from 1 to 22 based on size, arranged from largest to smallest. The full set of chromosomes makes up the genome.

I am only a programmer who is self-learning biology, but this caught my eye as confusing compared to other things I have learned. Is it accurate to refer to chromosomes as singular units containing 2 DNA molecules, rather than _pairs_ of chromosomes that each have one DNA molecule, inherited one from the father or the mother? Should this language be cleaned up a bit to consistently refer to pairs or not refer to pairs? My concern is that if one reads "**22 autosomes... and a pair of sex chromosomes**," that could be misinterpreted as a total of 24 chromosomes. I think what is really meant is "22 _pairs_ of autosomes... and a pair of sex chromosomes" for 23 total pairs, or 46 total chromosomes.

Of course things get more complicated with the haploid egg/sperm cells, and I realize you are sacrificing some details for simplicity. However I am concerned that the current description is somewhat inconsistent and confusing.

**Comment by claymcleod** [comment]
Oh good catch! I'll correct this language.

**Comment by claymcleod** [comment]
@joshuahedlund see what you think about the changes above, I think that cleans it up but let me know if you still find it lacking.
