### ISSUE TITLE
Grammar error: Missing word "a"

### ISSUE THREAD

**Issue by BenSlivka** [stjude/learngenomics.dev#3]
In this sentence: For humans, there are normally 22 autosomes (chromosomes shared by both sexes) and pair of sex chromosomes (XX for females or XY for males).
SHOULD be "and A pair of sex chromosomes".
--Ben
See https://learngenomics.dev/docs/biological-foundations/cells-genomes-dna-chromosomes

**Comment by claymcleod** [comment]
Thanks Ben!

**Comment by BenSlivka** [comment]
Happy to help!
(I was trying to figure out how to make a pull request, but it’s been a few decades since I last did source control – at Microsoft ca. 1994)
I’ve been reading on biology/genomics since 2015, helped David Baker at www.ipd.uw.edu<http://www.ipd.uw.edu> with his fundraising during the last UW $5B campaign.
Have “angel” investments in five biotech start-ups here in Seattle.
Cheers!
--Ben
www.benslivka.com<http://www.benslivka.com>
+1.206.910.0744 mobile
