### ISSUE TITLE
Unable to load learngenomics.dev

### ISSUE THREAD

**Issue by meanmachin3** [stjude/learngenomics.dev#9]
Firstly, many thanks for the website. I am unable to load the website learngenomics.dev. 

Running in to `ERR_NAME_NOT_RESOLVED `. I've attached screen grab for reference.

<img width="1790" alt="Screen Shot 2022-11-09 at 7 28 34 PM" src="https://user-images.githubusercontent.com/7353585/200993828-baad1f9e-aa48-475a-bb3b-e89eaadea971.png">

```bash
learngenomics.dev on  main is 📦 v0.0.0 via ⬢ v16.13.0
➜ curl https://learngenomics.dev/
curl: (6) Could not resolve host: learngenomics.dev

learngenomics.dev on  main is 📦 v0.0.0 via ⬢ v16.13.0
➜ curl http://learngenomics.dev/
curl: (6) Could not resolve host: learngenomics.dev
```

**Comment by abhishek-1131** [comment]
same issue at my end!

**Comment by claymcleod** [comment]
Hi both,

Sorry we just migrated the domain! It should be back up and running now. Let me know if you run into any issues!
